2013-04-26 18:01:50 INFO  AUTO-RUN [Case:FrameTest=>frametest]开始对xml的List资源进行扫描....</br>
2013-04-26 18:01:50 INFO  AUTO-RUN [Case:FrameTest=>frametest]扫描收集了List资源->产品链接</br>
2013-04-26 18:01:50 INFO  AUTO-RUN [Case:FrameTest=>frametest]扫描List资源完毕...</br>
2013-04-26 18:01:50 INFO  AUTO-RUN [Case:FrameTest=>frametest]开始对xml资源进行扫描....</br>
2013-04-26 18:01:50 INFO  AUTO-RUN [Case:FrameTest=>frametest]扫描收集了资源->百度首页-搜索框</br>
2013-04-26 18:01:50 INFO  AUTO-RUN [Case:FrameTest=>frametest]扫描收集了资源->百度首页-搜索按钮</br>
2013-04-26 18:01:50 INFO  AUTO-RUN [Case:FrameTest=>frametest]扫描收集了资源->测评游戏</br>
2013-04-26 18:01:50 INFO  AUTO-RUN [Case:FrameTest=>frametest]扫描收集了资源->测评模式</br>
2013-04-26 18:01:50 INFO  AUTO-RUN [Case:FrameTest=>frametest]扫描收集了资源->测评得分</br>
2013-04-26 18:01:50 INFO  AUTO-RUN [Case:FrameTest=>frametest]扫描收集了资源->测评显卡均价</br>
2013-04-26 18:01:50 INFO  AUTO-RUN [Case:FrameTest=>frametest]扫描收集了资源->MW-平板列表-苹果</br>
2013-04-26 18:01:50 INFO  AUTO-RUN [Case:FrameTest=>frametest]扫描收集了资源->百度-联想</br>
2013-04-26 18:01:50 INFO  AUTO-RUN [Case:FrameTest=>frametest]扫描XML资源完毕...</br>
2013-04-26 18:01:50 INFO  AUTO-RUN [Case:FrameTest=>frametest]开始扫描txt的资源元素...</br>
2013-04-26 18:01:50 INFO  AUTO-RUN [Case:FrameTest=>frametest]txt资源扫描结束</br>
2013-04-26 18:01:52 INFO  AUTO-RUN [Case:FrameTest=>frametest]扫描file类型的class文件...</br>
2013-04-26 18:01:52 INFO  AUTO-RUN [Case:FrameTest=>frametest]扫描file类型的class文件...</br>
2013-04-26 18:01:52 INFO  AUTO-RUN [Case:FrameTest=>frametest]开始扫描动作监听器......</br>
2013-04-26 18:01:52 INFO  AUTO-RUN [Case:FrameTest=>frametest]扫描动作监听器结束</br>
2013-04-26 18:01:53 INFO  AUTO-RUN [Case:FrameTest=>frametest]使用浏览器HtmlUnit进行自动化测试，将要打开网址http://product.it168.com/list/b/03010377_1.shtml测试</br>
2013-04-26 18:01:58 ERROR AUTO-RUN >>>>>>>>>>>>>>>测试用例执行失败>>>>>>>>>>></br>
2013-04-26 18:01:58 ERROR AUTO-RUN org.sky.auto.exception.MyAutoException</br>
2013-04-26 18:01:58 ERROR AUTO-RUN </br>
2013-04-26 18:01:58 ERROR AUTO-RUN org.sky.auto.exception.MyAutoException</br>
	at org.sky.auto.test.FrameTest.frametest(FrameTest.java:22)</br>
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)</br>
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)</br>
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)</br>
	at java.lang.reflect.Method.invoke(Method.java:597)</br>
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)</br>
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)</br>
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)</br>
	at org.sky.auto.runner.statement.InterceptorStatement.evaluate(InterceptorStatement.java:29)</br>
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)</br>
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)</br>
	at org.databene.feed4junit.Feeder.runChild(Feeder.java:194)</br>
	at org.databene.feed4junit.ChildRunner.run(ChildRunner.java:58)</br>
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)</br>
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)</br>
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)</br>
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)</br>
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)</br>
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)</br>
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)</br>
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)</br>
	at java.lang.Thread.run(Thread.java:680)</br>
</br>
2013-04-26 18:01:58 INFO  AUTO-RUN >>>>>>>>>>>>>>>测试用例执行结束>>>>>>>>>>></br>
2013-04-26 18:01:58 INFO  AUTO-RUN [Case:FrameTest=>frametest]关闭了所有的浏览器！</br>
2013-04-26 18:01:58 INFO  AUTO-RUN >>>>>>>>>>>>>>>测试用例执行开始>>>>>>>>>>></br>
2013-04-26 18:01:58 INFO  AUTO-RUN [Case:FrameTest=>baidu]开始扫描txt的资源元素...</br>
2013-04-26 18:01:58 INFO  AUTO-RUN [Case:FrameTest=>baidu]txt资源扫描结束</br>
2013-04-26 18:01:58 INFO  AUTO-RUN [Case:FrameTest=>baidu]扫描file类型的class文件...</br>
2013-04-26 18:01:58 INFO  AUTO-RUN [Case:FrameTest=>baidu]扫描file类型的class文件...</br>
2013-04-26 18:01:58 INFO  AUTO-RUN [Case:FrameTest=>baidu]开始扫描动作监听器......</br>
2013-04-26 18:01:58 INFO  AUTO-RUN [Case:FrameTest=>baidu]扫描动作监听器结束</br>
2013-04-26 18:01:58 INFO  AUTO-RUN [Case:FrameTest=>baidu]使用浏览器HtmlUnit进行自动化测试，将要打开网址http://www.baidu.com测试</br>
2013-04-26 18:01:58 INFO  AUTO-RUN [Case:FrameTest=>baidu][百度首页-搜索框]是来自XML的资源</br>
2013-04-26 18:01:59 INFO  AUTO-RUN [Case:FrameTest=>baidu]>>[百度首页-搜索框]输入值[北京]成功！</br>
2013-04-26 18:01:59 INFO  AUTO-RUN [Case:FrameTest=>baidu][百度首页-搜索按钮]是来自XML的资源</br>
2013-04-26 18:01:59 INFO  AUTO-RUN [Case:FrameTest=>baidu]>>[百度首页-搜索按钮]点击成功！</br>
2013-04-26 18:01:59 INFO  AUTO-RUN [Case:FrameTest=>baidu]关闭了所有的浏览器！</br>
2013-04-26 18:01:59 INFO  AUTO-RUN >>>>>>>>>>>>>>>测试用例执行结束>>>>>>>>>>></br>
2013-04-26 18:01:59 INFO  AUTO-RUN >>>>>>>>>>>>>>>测试用例执行开始>>>>>>>>>>></br>
2013-04-26 18:01:59 INFO  AUTO-RUN [Case:FrameTest=>testlist]开始扫描txt的资源元素...</br>
2013-04-26 18:01:59 INFO  AUTO-RUN [Case:FrameTest=>testlist]txt资源扫描结束</br>
2013-04-26 18:01:59 INFO  AUTO-RUN [Case:FrameTest=>testlist]扫描file类型的class文件...</br>
2013-04-26 18:01:59 INFO  AUTO-RUN [Case:FrameTest=>testlist]扫描file类型的class文件...</br>
2013-04-26 18:01:59 INFO  AUTO-RUN [Case:FrameTest=>testlist]开始扫描动作监听器......</br>
2013-04-26 18:01:59 INFO  AUTO-RUN [Case:FrameTest=>testlist]扫描动作监听器结束</br>
2013-04-26 18:02:00 INFO  AUTO-RUN [Case:FrameTest=>testlist]使用浏览器HtmlUnit进行自动化测试，将要打开网址http://www.it168.com/测试</br>
2013-04-26 18:02:01 INFO  AUTO-RUN [仓库]有子元素,定位方式为:By->tagName,Value->a,Index->null</br>
2013-04-26 18:02:01 WARN  AUTO-RUN CSS error: 'http://www.it168.com/' [12:2] Error in style rule. (Invalid token "html". Was expecting one of: , <LBRACE>, <COMMA>, <HASH>, ".", ":", "[", .)</br>
2013-04-26 18:02:01 WARN  AUTO-RUN CSS warning: 'http://www.it168.com/' [12:2] Ignoring the following declarations in this rule.</br>
2013-04-26 18:02:01 WARN  AUTO-RUN CSS error: 'http://www.it168.com/' [168:47] Error in style rule. (Invalid token "*". Was expecting one of: <EOF>, , <IDENT>, "}", ";".)</br>
2013-04-26 18:02:01 WARN  AUTO-RUN CSS warning: 'http://www.it168.com/' [168:47] Ignoring the following declarations in this rule.</br>
2013-04-26 18:02:01 WARN  AUTO-RUN CSS error: 'http://www.it168.com/' [204:97] Error in style rule. (Invalid token ":". Was expecting one of: <EOF>, , <NUMBER>, "inherit", <IDENT>, <STRING>, <PLUS>, <COMMA>, <HASH>, <IMPORTANT_SYM>, <EMS>, <EXS>, <LENGTH_PX>, <LENGTH_CM>, <LENGTH_MM>, <LENGTH_IN>, <LENGTH_PT>, <LENGTH_PC>, <ANGLE_DEG>, <ANGLE_RAD>, <ANGLE_GRAD>, <TIME_MS>, <TIME_S>, <FREQ_HZ>, <FREQ_KHZ>, <PERCENTAGE>, <DIMENSION>, <URI>, <FUNCTION>, "}", ";", "/", "-".)</br>
2013-04-26 18:02:01 WARN  AUTO-RUN CSS warning: 'http://www.it168.com/' [204:97] Ignoring the following declarations in this rule.</br>
2013-04-26 18:02:01 WARN  AUTO-RUN CSS error: 'http://www.it168.com/' [383:156] Error in expression. (Invalid token "eval(". Was expecting one of: , <NUMBER>, <IDENT>, <STRING>, <PLUS>, <COMMA>, <URI>, "-", "=".)</br>
2013-04-26 18:02:01 WARN  AUTO-RUN CSS error: 'http://www.it168.com/' [384:126] Error in expression. (Invalid token "eval(". Was expecting one of: , <NUMBER>, <IDENT>, <STRING>, <PLUS>, <COMMA>, <URI>, "-", "=".)</br>
2013-04-26 18:02:01 WARN  AUTO-RUN CSS error: 'http://www.it168.com/' [384:168] Error in style rule. (Invalid token "_position". Was expecting one of: <EOF>, "}", ";".)</br>
2013-04-26 18:02:01 WARN  AUTO-RUN CSS warning: 'http://www.it168.com/' [384:168] Ignoring the following declarations in this rule.</br>
2013-04-26 18:02:01 INFO  AUTO-RUN [Case:FrameTest=>testlist][Element]得到文本内容为[笔记本及平板]</br>
2013-04-26 18:02:01 INFO  AUTO-RUN [Case:FrameTest=>testlist]关闭了所有的浏览器！</br>
2013-04-26 18:02:01 INFO  AUTO-RUN >>>>>>>>>>>>>>>测试用例执行结束>>>>>>>>>>></br>
