package org.sky.auto.driver;
public enum Browser {
	IE,
	Firefox,
	Chrome,
	Safari,
	Opera,
	HtmlUnit,
	RemoteFirefox,
	RemoteIE,
	RemoteChrome,
	RemoteHtmlUnit,
	RemoteOpera,
	RemoteSafari,
//	ThreadRemoteSafari,
//	ThreadRemoteFirefox,
//	ThreadRemoteChrome,
//	ThreadRemoteIE,
//	ThreadRemoteHtmlUnit,
//	ThreadIE,
//	ThreadFirefox,
//	ThreadChrome,
//	ThreadSafari,
//	ThreadHtmlUnit,
	NULL;
}
